# Generated by Django 4.2.7 on 2025-08-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True, verbose_name='Năm học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Năm học hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Năm học',
                'verbose_name_plural': 'Năm học',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã danh mục')),
                ('category_type', models.CharField(choices=[('general', 'Đại cương'), ('foundation', 'Cơ sở'), ('major', 'Chuyên ngành'), ('elective', 'Tự chọn'), ('thesis', 'Luận văn/Đồ án')], max_length=20, verbose_name='Loại danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('min_credits', models.IntegerField(default=0, verbose_name='Tín chỉ tối thiểu')),
                ('max_credits', models.IntegerField(blank=True, null=True, verbose_name='Tín chỉ tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục môn học',
                'verbose_name_plural': 'Danh mục môn học',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('version', models.CharField(max_length=10, verbose_name='Phiên bản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chương trình đào tạo',
                'verbose_name_plural': 'Chương trình đào tạo',
                'ordering': ['-academic_year', 'major', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khoa')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã khoa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Khoa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chuyên ngành')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Mã ngành')),
                ('degree_type', models.CharField(choices=[('bachelor', 'Cử nhân'), ('master', 'Thạc sĩ'), ('doctor', 'Tiến sĩ'), ('associate', 'Cao đẳng')], default='bachelor', max_length=20, verbose_name='Loại bằng')),
                ('duration_years', models.IntegerField(default=4, verbose_name='Thời gian đào tạo (năm)')),
                ('total_credits', models.IntegerField(default=140, verbose_name='Tổng số tín chỉ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chuyên ngành')),
                ('career_prospects', models.TextField(blank=True, null=True, verbose_name='Triển vọng nghề nghiệp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chuyên ngành',
                'verbose_name_plural': 'Chuyên ngành',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Tên lớp')),
                ('year_of_study', models.IntegerField(verbose_name='Năm học')),
                ('max_students', models.IntegerField(default=40, verbose_name='Sĩ số tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['academic_year', 'major', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='core_course_academi_8d6466_idx',
            old_name='core_course_academi_16c7e9_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='assessment_method',
            field=models.TextField(blank=True, null=True, verbose_name='Phương pháp đánh giá'),
        ),
        migrations.AddField(
            model_name='course',
            name='assistant_teachers',
            field=models.ManyToManyField(blank=True, related_name='assisting_courses', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên hỗ trợ'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Cơ bản'), ('intermediate', 'Trung bình'), ('advanced', 'Nâng cao'), ('expert', 'Chuyên sâu')], default='intermediate', max_length=20, verbose_name='Độ khó'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Học trực tuyến'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='Tiếng Việt', max_length=50, verbose_name='Ngôn ngữ giảng dạy'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='Mục tiêu học tập'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_courses', to='core.course', verbose_name='Môn học tiên quyết'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credits_earned',
            field=models.IntegerField(default=0, verbose_name='Số tín chỉ đã tích lũy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Điểm trung bình tích lũy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.academicyear', verbose_name='Năm học'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_classes', to=settings.AUTH_USER_MODEL, verbose_name='Cố vấn học tập'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.major', verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='core.department', verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='department',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng khoa'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.academicyear', verbose_name='Năm học áp dụng'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_curriculums', to=settings.AUTH_USER_MODEL, verbose_name='Được phê duyệt bởi'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.major', verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.coursecategory', verbose_name='Danh mục môn học'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department', verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department', verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.academicyear', verbose_name='Năm học nhập học'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.major', verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studentclass', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.academicyear', verbose_name='Năm học'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('major', 'academic_year', 'version')},
        ),
    ]
