# Generated by Django 4.2.7 on 2025-08-10 16:05

import core.models.documents
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_academicyear_coursecategory_curriculum_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('file', models.FileField(upload_to=core.models.documents.document_upload_path, verbose_name='File tài liệu')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('file_size', models.BigIntegerField(verbose_name='Kích thước file (bytes)')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('gif', 'GIF'), ('mp4', 'MP4'), ('mp3', 'MP3'), ('zip', 'ZIP'), ('rar', 'RAR'), ('other', 'Khác')], max_length=10, verbose_name='Loại file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tải lên')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('archived', 'Đã lưu trữ'), ('deleted', 'Đã xóa')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('visibility', models.CharField(choices=[('public', 'Công khai'), ('private', 'Riêng tư'), ('course_only', 'Chỉ môn học')], default='public', max_length=20, verbose_name='Quyền xem')),
                ('download_count', models.IntegerField(default=0, verbose_name='Số lần tải về')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần tải về cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tải')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='core.document', verbose_name='Tài liệu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to=settings.AUTH_USER_MODEL, verbose_name='Người tải')),
            ],
            options={
                'verbose_name': 'Log tải tài liệu',
                'verbose_name_plural': 'Log tải tài liệu',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bình luận')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.document', verbose_name='Tài liệu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
            ],
            options={
                'verbose_name': 'Bình luận tài liệu',
                'verbose_name_plural': 'Bình luận tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Màu sắc')),
                ('icon', models.CharField(default='fas fa-file', max_length=50, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_document_categories', to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi')),
            ],
            options={
                'verbose_name': 'Danh mục tài liệu',
                'verbose_name_plural': 'Danh mục tài liệu',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.documentcategory', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='document',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.course', verbose_name='Môn học'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên'),
        ),
    ]
