# Generated by Django 4.2.7 on 2025-08-11 16:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_document_documentdownloadlog_documentcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: 20IT1, 21KT2, 22QT3...', max_length=50, unique=True, verbose_name='Tên lớp')),
                ('display_name', models.CharField(help_text='Tên đầy đủ của lớp, ví dụ: Lớp Công nghệ thông tin K20', max_length=100, verbose_name='Tên hiển thị')),
                ('academic_year', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], help_text='Năm sinh viên nhập học', verbose_name='Năm học')),
                ('department', models.CharField(choices=[('IT', 'Công nghệ thông tin'), ('KT', 'Kế toán'), ('QT', 'Quản trị kinh doanh'), ('NN', 'Ngoại ngữ'), ('KT', 'Kinh tế'), ('KH', 'Khoa học'), ('GD', 'Giáo dục'), ('YT', 'Y tế'), ('XH', 'Xã hội học'), ('KHAC', 'Khác')], max_length=10, verbose_name='Khoa/Ngành')),
                ('class_number', models.IntegerField(help_text='Số thứ tự của lớp trong khoa (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Số lớp')),
                ('max_students', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Sĩ số tối đa')),
                ('current_students', models.IntegerField(default=0, verbose_name='Sĩ số hiện tại')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm ngưng'), ('graduated', 'Đã tốt nghiệp'), ('suspended', 'Tạm đình chỉ')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, help_text='Thông tin bổ sung về lớp học', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('advisor', models.ForeignKey(blank=True, help_text='Giảng viên cố vấn cho lớp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_advised_classes', to=settings.AUTH_USER_MODEL, verbose_name='Cố vấn học tập')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_created_classes', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('head_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_headed_classes', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên chủ nhiệm')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['-academic_year', 'department', 'class_number'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enrolled_students', to='core.class', verbose_name='Lớp đang theo học'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year', 'department'], name='core_class_academi_642e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['status'], name='core_class_status_377ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['advisor'], name='core_class_advisor_c21cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['head_teacher'], name='core_class_head_te_9a3ff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('academic_year', 'department', 'class_number')},
        ),
    ]
