# Generated by Django 4.2.7 on 2025-08-13 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_class_userprofile_class_enrolled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/files/', verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file_type', models.CharField(max_length=50, verbose_name='Loại file')),
                ('file_size', models.BigIntegerField(verbose_name='Kích thước file (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('is_submission_file', models.BooleanField(default=False, verbose_name='Là file bài nộp')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả file')),
            ],
            options={
                'verbose_name': 'File bài tập',
                'verbose_name_plural': 'File bài tập',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm số')),
                ('feedback', models.TextField(verbose_name='Nhận xét chi tiết')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian chấm điểm')),
                ('is_final', models.BooleanField(default=True, verbose_name='Điểm cuối cùng')),
                ('criteria_scores', models.JSONField(default=dict, verbose_name='Điểm theo tiêu chí')),
                ('rubric_used', models.JSONField(default=dict, verbose_name='Rubric sử dụng')),
            ],
            options={
                'verbose_name': 'Điểm bài tập',
                'verbose_name_plural': 'Điểm bài tập',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='core_assign_course__3043a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='core_assign_status_7d23cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='core_assign_assignm_4b7728_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='core_assign_priorit_f8fc5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignmentsubmission',
            name='core_assign_assignm_afe291_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignmentsubmission',
            name='core_assign_student_4e98fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignmentsubmission',
            name='core_assign_status_8e2228_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='max_submissions',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submission_deadline',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='weight',
        ),
        migrations.AddField(
            model_name='assignment',
            name='allowed_file_types',
            field=models.JSONField(default=list, verbose_name='Loại file được phép'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Hướng dẫn làm bài'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_visible_to_students',
            field=models.BooleanField(default=False, verbose_name='Hiển thị cho sinh viên'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_file_size',
            field=models.IntegerField(default=10, verbose_name='Kích thước file tối đa (MB)'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Ghi chú của sinh viên'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm số'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Chấm điểm bởi'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='Mô tả bài tập'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm tối đa'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('draft', 'Bản nháp')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề bài tập'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Nhận xét'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'status'], name='core_assign_course__d5856b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', 'status'], name='core_assign_created_3a5423_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='core_assign_assignm_09a883_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'status'], name='core_assign_student_565b61_idx'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grades', to=settings.AUTH_USER_MODEL, verbose_name='Chấm điểm bởi'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_grade', to='core.assignmentsubmission', verbose_name='Bài nộp'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.assignment', verbose_name='Bài tập'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assignment_files', to=settings.AUTH_USER_MODEL, verbose_name='Upload bởi'),
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='content',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='submission_number',
        ),
        migrations.AddIndex(
            model_name='assignmentgrade',
            index=models.Index(fields=['submission'], name='core_assign_submiss_3789ad_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentgrade',
            index=models.Index(fields=['graded_by'], name='core_assign_graded__ebc2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentfile',
            index=models.Index(fields=['assignment', 'is_submission_file'], name='core_assign_assignm_c12025_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentfile',
            index=models.Index(fields=['uploaded_by'], name='core_assign_uploade_017f36_idx'),
        ),
    ]
