# Generated by Django 4.2.7 on 2025-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignmentfile_assignmentgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/', verbose_name='File đính kèm'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('closed', 'Đã đóng')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
