# Generated by Django 4.2.7 on 2025-08-13 15:22

import core.models.assignment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_attachment_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='allowed_file_types',
            field=models.JSONField(default=core.models.assignment.default_allowed_file_types, verbose_name='Loại file được phép'),
        ),
    ]
